import {
  v4 as uuid
} from 'uuid'

let inventory = [
  {
    categories: ['all products', 'decorative microcement and acrylic ready mixed coatings','walls','best selling','microcement and acrylic ready mixed coatings'],
    name: 'Microcement "M-12"',
    subtitle:'Flexible microcement for walls and floors',
    price: '1000',
    image: 'https://i.imgur.com/CRH4a8v.png',
    description: `Ready-made, white or colored cement mortar, suitable for application on vertical and horizontal surfaces, indoors and outdoors. 
    Its special fiber-reinforced formula contains high strength cement, suitably graded aggregates, special active additives and top quality resins providing flexibility, unbreakable adhesion to the substrate, great workability and a perfect finish surface with high mechanical strengths. 
    It ‘follows’ expansions and contractions effectively and does not crack by them. Unaffected by small vibrations, it is resistant to rapid temperature variations and adverse weather conditions. Its advanced composition does not ‘require’ addition - enhancement with improving emulsions.`,
    classified: `Classified PCC R3 per EN 1504-3 and as floor screed material is classified CT-C30-F7-AR2 per EN 13813.`,
    brand: 'Baufixit',
    packaging: '25kg',
    consumption: '7kg/m² per 5mm thick coat',
    colors: 'White - White Ice - Light gray - Dark gray - Aqua Marine - Alabaster - Sun ray - Pistachio',
    currentInventory: 4
  },
  {
    categories: ['all products', 'basements and tanks','wet areas', 'best selling'],
    name: 'Water Stop',
    subtitle:'Waterproofing cement-based slurry for basements and tanks',
    price: '1000',
    image: 'https://i.imgur.com/o5y85IC.png',
    description: 'Waterproofing cement-based slurry for basements and tanks. Provides total waterproofing against hydrostatic pressure up to 5 atm. Suitable for potable water tanks. Ideal for internal (negative side) waterproofing of below ground structures, since it can withstand negative hydrostatic pressure.',
    classified: ` CE marking according to harmonized European Standards (EN).`,
    brand: 'Baufixit',
    packaging: '18 kg',
    consumption: '2.0-4.0 kg/m²',
    colors: 'Grey',
    currentInventory: 4
  },
  {
    categories: ['all products', 'thermal insulation board adhesives'],
    name: 'PKB 99',
    subtitle:'Fiber-reinforced, polymer-modified, cement-based adhesive for thermal insulation boards',
    price: '1000',
    image: 'https://i.imgur.com/iCPtWJO.png',
    description: 'Fiber-reinforced, polymer-modified, cement-based adhesive for thermal insulation boards. Ideal for bonding polystyrene insulation boards to cementitious substrates. Can also be applied to facade insulation boards with reinforcing fiberglass mesh, serving as the ideal substrate for the subsequent coat of render.',
    classified: ` CE marking according to harmonized European Standards (EN).`,
    brand: 'Baufixit',
    packaging: '25 kg',
    consumption: 'As adhesive: 3.0-4.0 kg/m². As reinforced mortar: ≈ 1.5 kg/m²/mm.',
    colors: 'Gray',
    currentInventory: 4
  },
  {
    categories: ['all products', 'thermal insulation board adhesives'],
    name: 'PKB 100',
    subtitle:'High-performance, fiber-reinforced, polymer-modified, cement-based adhesive and base coat for thermal insulation boards',
    price: '1000',
    image: 'https://i.imgur.com/itmyG1E.png',
    description: 'High-performance, fiber-reinforced, polymer-modified, cement-based adhesive and base coat for thermal insulation boards. Features no vertical slip and extended open time. Suitable for bonding polystyrene insulation boards to building facades. Can also be used as a base coat with reinforcing fiberglass mesh on facade insulation boards, serving as the ideal substrate for the subsequent coat of render.',
    classified: ` CE marking according to harmonized European Standards (EN).`,
    brand: 'Baufixit',
    packaging: '25 kg',
    consumption: 'As adhesive: 2.0-4.0 kg/m². As reinforced mortar: ≈ 1.5 kg/m²/mm.',
    colors: 'Gray - White',
    currentInventory: 4
  },
  {
    categories: ['all products', 'basements and tanks', 'wet areas','best selling'],
    name: 'Water Stop Super Elastic',
    subtitle:'Waterproofing cement-based slurry, resistant to sulfates',
    price: '1000',
    image: 'https://i.imgur.com/eq375i0.png',
    description: 'Ultra-flexible, 2-component, polymer-modified, waterproofing cement-based slurry. Ideal for waterproofing of surfaces formed by concrete, render, gypsum board, masonry, cement blocks, metal, etc., that show or are expected to show hairline cracks due to expansion-contraction or vibration, such as flat roofs, balconies, swimming pools, above ground tanks, inverted roofs, etc.',
    classified: ` CE marking according to harmonized European Standards (EN). Root-resistant material.`,
    brand: 'Baufixit',
    packaging: '18 kg',
    consumption: '2.0-4.0 kg/m²',
    colors: 'White',
    currentInventory: 4
  },
  {
    categories: ['all products', 'tile adhesives', 'natural stone adhesives','best selling'],
    name: 'SFK 18',
    subtitle:'High-performance, ultra-flexible, polymer-modified, cement-based tile adhesive',
    price: '1000',
    image: 'https://i.imgur.com/3R2nsz0.png',
    description: 'High-performance, elastic, 2-component, cement-based tile adhesive. Application fields: For fixing all types of wall and floor tiles to vibrating or dimensionally unstable substrates, e.g. gypsum board, chipboard, heated floors, balconies, swimming pools, etc. Combined with the 2-component, highly flexible, waterproofing cement-based slurry WATER STOP ELASTIC, a perfect waterproofing-tiling system ideal for highly demanding applications is obtained.',
    classified: ` CE marking according to harmonized European Standards (EN).`,
    brand: 'Baufixit',
    packaging: '18 kg',
    consumption: '1.5-4.0 kg/m²',
    colors: 'White - Grey',
    currentInventory: 4
  },
  {
    categories: ['all products', 'basements and tanks','wet areas', 'best selling'],
    name: 'Water Stop Elastic',
    subtitle:'Highly flexible, 2-component, polymer-modified, waterproofing cement-based slurry',
    price: '1000',
    image: 'https://i.imgur.com/iYJdL17.png',
    description: 'Highly flexible, 2-component, polymer-modified, waterproofing cement-based slurry. Similar to Water Stop and even more suitable for waterproofing of surfaces that show or are expected to show hairline cracks caused by expansion-contraction or vibration, such as flat roofs, swimming pools, tunnels, above ground tanks, etc. Ideal for waterproofing under tiles in combination with the tile adhesive BAUFIXIT FKS 14. Very low VOC emissions, subject to regulations to ensure safe handling.',
    classified: ` CE marking according to harmonized European Standards (EN). Root-resistant material.`,
    brand: 'Baufixit',
    packaging: '18 kg (A+B)',
    consumption: '2.0-4.0 kg/m²',
    colors: 'Grey - White',
    currentInventory: 4
  },
  {
    categories: ['all products','tile adhesives', 'natural stone adhesives'],
    name: 'FFK 16',
    subtitle:'High-performance, extra-flexible, polymer-modified, cement-based tile adhesive',
    price: '1000',
    image: 'https://i.imgur.com/mXRekUS.png',
    classified: ` CE marking according to harmonized European Standards (EN).`,
    description: 'High-performance, extra-flexible, polymer-modified, cement-based tile adhesive. Features no vertical slip and extended open time. Application fields: For fixing all types of wall and floor tiles, including absorbent and non-absorbent tiles, large-format tiles, glass mosaics, etc., to demanding substrates requiring high adhesion, extra flexibility and moisture resistance, e.g. heated floors, metal surfaces, gypsum boards, swimming pools, etc. For interior and exterior use.',
    brand: 'Baufixit',
    packaging: '25 kg',
    consumption: '1.5-4.0 kg/m²',
    colors: 'Grey - White',
    currentInventory: 4
  },
  {
    categories: ['all products','tile adhesives'],
    name: 'FKS 14',
    subtitle:'High-performance, polymer-modified, cement-based tile adhesive',
    price: '1000',
    image: 'https://i.imgur.com/eLZOxYw.png',
    classified: ` CE marking according to harmonized European Standards (EN).`,
    description: 'High-performance, polymer-modified, cement-based tile adhesive. Features no vertical slip and extended open time. Application fields: Suitable for fixing of ceramic and natural stone tiles to walls and floors, to substrates requiring high adhesion and moisture resistance. For interior and exterior use.',
    brand: 'Baufixit',
    packaging: '25 kg',
    consumption: '1.5-4.0 kg/m²',
    colors: 'Grey - White',
    currentInventory: 4
  },
  {
    categories: ['all products','tile adhesives'],
    name: 'Stuko Pllakash "S5"',
    subtitle:'High-performance, designer, highly water-repellent, colored, quick-setting, polymer-modified, cement-based tile grout CG2 WA',
    price: '1000',
    image: 'https://i.imgur.com/hLwjia6.png',
    classified: `Very low VOC emissions, the strictest quality label for low emission products.`,
    description: 'High-performance, designer, highly water-repellent, colored, quick-setting, polymer-modified, cement-based tile grout CG2 WA. Thanks to its cement-free formulation, it ensures perfect color uniformity and prevents the appearance of salt and lime deposits, while being more user-friendly, i.e. non-irritating. Features great water-repellency with drop-effect and high mechanical strength. Containing special bacteriostatic agents, it prevents the growth of bacteria in the joints. Ideal for joint width 1-12 mm. Intended for internal and external grouting of all floor and wall tile types.',
    brand: 'Baufixit',
    packaging: '25 kg',
    consumption: '0.2-2.0 kg/m², depending on tile size and joint width',
    colors: 'White - Black - Gray - Beige - Brown - Powder',
    currentInventory: 4
  },
  {
    categories: ['all products', 'cement based powder fillers'],
    name: 'BauStucco "B1"',
    subtitle:'Ultra fine-grained, polymer-modified, cement-based interior powder filler',
    price: '1000',
    image: 'https://i.imgur.com/0Msjhil.png',
    classified: `CE marking according to harmonized European Standards (EN). Very low VOC emissions, the strictest quality label for low emission products.`,
    description: 'Ultra fine-grained, polymer-modified, cement-based interior powder filler. For smoothing and preparing wall surfaces made of concrete or plaster prior to painting. Replaces oil putties and other similar materials.',
    brand: 'Baufixit',
    packaging: '25 kg',
    consumption: 'Approx. 1.1 kg/m²/mm of render thickness',
    colors: 'White',
    currentInventory: 4
  },
  {
    categories: ['all products', 'silicone ready mixed renders'],
    name: 'Grafiato Akrilike Shtese',
    subtitle:'Acrylic, ready-mixed, exceptionally water-repellent render – Rough-textured finish',
    price: '1000',
    image: 'https://i.imgur.com/Nzuwc82.png',
    classified: ` CE marking according to harmonized European Standards (EN).`,
    description: 'Acrylic, ready-mixed, exceptionally water-repellent render. Rough-textured finish. Features exceptional hydrophobic properties and high breathability. Allows for faster workflow and project completion by forgoing the need for post painting. Thanks to its high elasticity and excellent adhesion to the surface, it is ideal for use as finish coat in external thermal insulation systems. Available in the following type and application thickness: GRAFIATO AKRILIKE SHTESE 2 mm.',
    brand: 'Baufixit',
    packaging: '25 kg',
    consumption: 'Approx. 1.6 kg/m²/mm of render thickness',
    colors: 'White - Gray',
    currentInventory: 4
  },
  {
    categories: ['all products', 'silicone ready mixed renders'],
    name: 'Grafiato Silikoni',
    subtitle:'Acrylic, ready-mixed, exceptionally water-repellent render – Smooth finish',
    price: '1000',
    image: 'https://i.imgur.com/IUH6QpS.png',
    classified: ` CE marking according to harmonized European Standards (EN).`,
    description: 'Acrylic, ready-mixed, exceptionally water-repellent render. Smooth finish. Features exceptional hydrophobic properties and high breathability. Allows for faster workflow and project completion by forgoing the need for post painting. Thanks to its high elasticity and excellent adhesion to the surface, it is ideal for use as finish coat in external thermal insulation systems. Depending on grain size, it is available in the following types and application thicknesses: GRAFIATO SILIKONI 1 mm. GRAFIATO SILIKONI 1.5 mm. GRAFIATO SILIKONI 2 mm.',
    brand: 'Baufixit',
    packaging: '25 kg',
    consumption: 'Approx. 1.8 kg/m²/mm of render thickness',
    colors: 'White and other colors upon order (min. quantity: 150 kg).',
    currentInventory: 4
  },
  {
    categories: ['all products', 'render primers'],
    name: 'BauPrimer "A3"',
    subtitle:'Render adhesion primer for smooth or non-porous substrates',
    price: '1000',
    image: 'https://i.imgur.com/qYTnoVo.png',
    classified: ` CE marking according to harmonized European Standards (EN).`,
    description: 'Render adhesion primer for smooth or non-porous substrates. For use as an alternative to spatterdash to enhance adhesion of the subsequent coat of plaster/render. For interior and exterior use. For outdoor applications, it is recommended to add cement (20% by weight). Ideal for gypsum plasters.',
    brand: 'Baufixit',
    packaging: '25 kg',
    consumption: '300-350 g/m², depending on layer thickness',
    colors: '',
    currentInventory: 4
  },
  {
    categories: ['all products','acrylic ready mixed renders', 'decorative microcement and acrylic ready mixed coatings'],
    name: 'BauCryl "G10"',
    subtitle:'Acrylic, ready-mixed, exceptionally water-repellent render – Smooth finish',
    price: '1000',
    image: 'https://i.imgur.com/tH6iKPB.png',
    classified: ` CE marking according to harmonized European Standards (EN).`,
    description: 'Acrylic, ready-mixed, exceptionally water-repellent render. Smooth finish. Features exceptional hydrophobic properties and high breathability. Allows for faster workflow and project completion by forgoing the need for post painting. Thanks to its high elasticity and excellent adhesion to the surface, it is ideal for use as finish coat in external thermal insulation systems. Depending on grain size, it is available in the following types and application thicknesses: BAUCRYL Fine 1 mm BAUCRYL Fine 1.5 mm. BAUCRYL Fine 2 mm.',
    brand: 'Baufixit',
    packaging: '25 kg',
    consumption: 'Approx. 1.8 kg/m²/mm of render thickness.',
    colors: 'White and other colors upon order (min. quantity: 150 kg)',
    currentInventory: 4
  },
  {
    categories: ['all products', 'flat roofs'],
    name: 'BauFlex',
    subtitle:'Elastomeric, liquid waterproofing membrane for flat roofs and tiled roofs',
    price: '1000',
    image: 'https://i.imgur.com/CVfk6AU.png',
    classified: `CE marking according to harmonized European Standards (EN).`,
    description: 'Elastomeric, liquid waterproofing membrane for flat roofs and tiled roofs. The white product is used for waterproofing of flat roofs that have at least a slight slope to naturally drain the water away. Forms a highly elastic and vapor-permeable membrane, without seams or joints, offering resistance to weather conditions and aging. Can also be used as a cool roof coating. The red-brown product is used for tiled roof waterproofing.',
    brand: 'Baufixit',
    packaging: '25 kg, 15 kg, 5 kg, 1 kg.',
    consumption: '1.0-1.5 kg/m².',
    colors: 'White - Red - Brown',
    currentInventory: 4
  },
  {
    categories: ['all products', 'flat roofs'],
    name: 'BauFlex B20',
    subtitle:'Elastomeric, liquid waterproofing membrane for flat roofs, based on acrylic and polyurethane resin',
    price: '1000',
    image: 'https://i.imgur.com/k1QL8sx.png',
    classified: ` CE marking according to harmonized European Standards (EN).`,
    description: 'Elastomeric, liquid waterproofing membrane for flat roofs, based on acrylic and polyurethane resins. Ideal for flat roofs subject to short-term ponding due to insufficient slope. Highly recommended for use in regions with very low temperatures. Forms an elastic and vapor-permeable membrane, without seams or joints, offering resistance to aging. Can also be used as a cool roof coating.',
    brand: 'Baufixit',
    packaging: '25 kg',
    consumption: '1.0-1.5 kg/m².',
    colors: 'White - Grey',
    currentInventory: 4
  },
]

inventory.map(i => {
  i.id = uuid()
  return i
})

export default inventory